### ISSUE TITLE
Matching the end of a string

### ISSUE THREAD

**Issue by malte-v** [skogsbaer/roundtrip#4]
First, thank you for making this great library! I've really enjoyed using it so far!
Do you have some sort of "end" combinator that only lets parsing succeed if there are no more characters to be parsed? If not, how would one go about implementing it? Thanks!

**Comment by ulidtko** [comment]
Hi @malte-v... Since `roundtrip-string` uses [parsec] (and even re-exports the `Text.Parsec` module wholesale) — I'm pretty sure you could use its [eof] combinator to achieve exactly that. 

[parsec]: https://hackage.haskell.org/package/parsec
[eof]: https://hackage.haskell.org/package/parsec-3.1.17.0/docs/Text-Parsec-Combinator.html#v:eof

**Comment by malte-v** [comment]
ok sounds good, thanks! i'm gonna close this then.
